# Generated by Django 5.0.3 on 2024-04-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_products_price_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product/product_images'),
        ),
    ]
