# Generated by Django 5.0.3 on 2024-04-03 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('images', models.ImageField(default='product.jpg', upload_to='product_images')),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('Category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_management.category')),
            ],
        ),
    ]
