# Generated by Django 5.0.3 on 2024-04-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_rename_category_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='category_id',
        ),
    ]
