# Generated by Django 5.0.3 on 2024-04-04 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_rename_category_products_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category_id',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_management.category'),
        ),
    ]
